#i18n:
#  structure: multiple_folders
#  locales: [nl, fr, en]
#  default_locale: nl

#logo_url: https://sintlukas.netlify.app/assets/site/logo.svg
locale: 'en'

backend:
  name: git-gateway
  branch: main
  repo: pmcp/kdm
  squash_merges: true


media_folder: /public/assets/uploads
public_folder: /assets/uploads


#publish_mode: editorial_workflow


slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"


collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'content'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'

      - label: 'Body'
        name: 'body'
        widget: 'markdown'

      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
